# Site settings
title:       Justin Davis
email:       justin@maderalabs.com
author:      Justin Davis
description: "UX guy. Javascript hacker. Co-founder of Crowdsync (crowdsync.io)."
baseurl:     ""
url:         "http://justindavis.co"

# Google analytics
google_analytics: UA-53680827-1

# Optional features
animated:           false
show_related_posts: true
show_post_footers:  true

# Social icons
show_social_icons: true
github_username: jwd2a
twitter_username: jwd2a
google_plus_id:
linkedin_username: jwd2a
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     kramdown
permalink:    pretty
paginate:     5
sass:
  compressed: true
gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed

# Defaults
defaults:
  - scope:
      type: building_jampay
    values:
      layout: building_jampay

# Collections
collections:
  building_jampay:
    output: true
    permalink: /building-jampay/:slug
